travis:
  secure:
    BINSTAR_TOKEN: WK0lKs4KBXr8iqmLE2EtKW3EZhVMMUqLzxJ/HgF8GVI5EGG6uywwRq/wR6BjxXldP484hlOENZ8sJVbwZPVyALls8hUlVEXNGczsF6C5S4n1vWHtCGLy3L1LyM0xopc9MPa7ad9DAGSuQlsA4Q3ot1cjd6ASFL986aJeI7cVBPZaEyzaeKwa1KTMwAvQLNXGg9ZFIcGPv22NAhxrBlwwOSkLPnAg8YQKB4STebtJvvPsO/Dx9/CbTCTTWdfG3WesnfeiIU7rpnjwd9R3KtGWQkMmK7d+xXPXgbUiAvMEN9OJ+S46aBtCK7Wx1d6D5OmEK/r7YvbvRmWiRk4iQMeaddBFRQuQ9gCWiBT7zlkyt6YRUdvbX/Rrm3o3lpxJIgTF6mYeloFzS7vHpSw0mbheL9uNmQaovSdavvLs7UjTAI+fxpY8MP6ECpAq/5j5AzyPhObiMsucpX2ickaWXKqry4dgGsEr4IZ1iQWUdlmpYq22Hd7bkqEqKsZyVWo0o7lVcygNLc6gv6Fuc1Be0QILCJKOVLtUdJQQlNMIEN2B7Kp5KrnACMmddigKjBaxXSwbSHCkHGICT6+q7F0GZeNiqEVEOXXFowrEKI5n+LrgLFIBTDWU9yZ+s18fiagWBzmHkv3a6Pyg6Pp2qK9Q9UoxOGWmVp90DrwYiYhWJURbK+c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
